version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/addons"
    versions:
    - 6.2.2
    - 6.2.4
    - 6.2.5
    - 6.2.6
    - 6.2.9
  - dependency-name: ts-loader
    versions:
    - 9.0.0
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.2.6
  - dependency-name: "@storybook/addon-docs"
    versions:
    - 6.2.3
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
  - dependency-name: netlify-cli
    versions:
    - 3.4.5
    - 3.4.6
    - 3.4.7
    - 3.5.0
    - 3.7.1
    - 3.8.0
    - 3.8.1
    - 3.8.3
    - 3.8.4
    - 3.8.5
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.2
    - 2.32.3
    - 2.32.4
  - dependency-name: gatsby-plugin-mdx
    versions:
    - 1.10.0
    - 1.9.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: gsap
    versions:
    - 3.6.0
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: "@mdx-js/react"
    versions:
    - 1.6.22
  - dependency-name: "@mdx-js/mdx"
    versions:
    - 1.6.22
  - dependency-name: graphql-playground-html
    versions:
    - 1.6.29
  - dependency-name: object-path
    versions:
    - 0.11.5
  - dependency-name: node-fetch
    versions:
    - 2.6.1
  - dependency-name: bl
    versions:
    - 1.2.3
  - dependency-name: decompress
    versions:
    - 4.2.1
  - dependency-name: dot-prop
    versions:
    - 4.2.1
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: netlify-plugin-gatsby-cache
    versions:
    - 0.3.2
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.9
  - dependency-name: gatsby-plugin-robots-txt
    versions:
    - 1.5.5
  - dependency-name: ini
    versions:
    - 1.3.8
