[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[build]
  publish = "_site"
  command = "DEBUG=* eleventy"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = false
  minify = true

[[plugins]]
  package = "./.netlify/slack"

[[redirects]]
  from = "/guides/2020-05-17-collaborative-ui-development"
  to = "/2020-05-17-collaborative-ui-development"

[[redirects]]
  from = "/guides/2020-05-02-continuous-integration-with-netlify-build-plugins"
  to = "/2020-05-02-continuous-integration-with-netlify-build-plugins"

[[redirects]]
  from = "/guides/"
  to = "/"

[[redirects]]
  from = "/repos/"
  to = "/"
