[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[build]
  publish = "public"

[[plugins]]
  package = "./.plugins/ci"

[[plugins]]
  package = "./.plugins/slack"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/guides/2020-05-17-collaborative-ui-development"
  to = "/2020-05-17-collaborative-ui-development"

[[redirects]]
  from = "/guides/2020-05-02-continuous-integration-with-netlify-build-plugins"
  to = "/2020-05-02-continuous-integration-with-netlify-build-plugins"

[[redirects]]
  from = "/guides/"
  to = "/"

[[redirects]]
  from = "/repos/"
  to = "/"